<a href="https://colab.research.google.com/github/bhavyavj/Google_Colab/blob/master/PYTHON_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
a=np.array([2,7,1,99,4])

In [0]:
type(a)

numpy.ndarray

In [0]:
b=np.array([12,17,11,199,14])

In [0]:
b

array([ 12,  17,  11, 199,  14])

In [0]:
a

array([ 2,  7,  1, 99,  4])

In [0]:
a[0]


2

In [0]:
a+b

array([ 14,  24,  12, 298,  18])

In [0]:
a+2

array([  4,   9,   3, 101,   6])

In [0]:
a*2

array([  4,  14,   2, 198,   8])

In [0]:
a**2

array([   4,   49,    1, 9801,   16])

In [0]:
x=np.array([[2,5,8],[3,6,1]])

In [0]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
x[0]


array([2, 5, 8])

In [0]:
x[0][0]

2

In [0]:
x[1]


array([3, 6, 1])

In [0]:
y=x+7


In [0]:
y


array([[ 9, 12, 15],
       [10, 13,  8]])

In [0]:
x*2

array([[ 4, 10, 16],
       [ 6, 12,  2]])

In [0]:
x**2

array([[ 4, 25, 64],
       [ 9, 36,  1]])

In [0]:
z=np.array([[2,7],[3,8],[2,9],[9,4]]
          )

In [0]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [0]:
x.shape


(2, 3)

In [0]:
z.shape


(4, 2)

In [0]:
z[0:2]


array([[2, 7],
       [3, 8]])

In [0]:
z[0:]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [0]:
z[0:,0]

array([2, 3, 2, 9])

In [0]:
z[0:2,0]

array([2, 3])

In [0]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [0]:
z[[0,2]]

array([[2, 7],
       [2, 9]])

In [0]:
z[[0,3],1]


array([7, 4])

In [0]:
b=np.array([[1,9,7],[3,2,8],[4,5,6],[2,9,0]])


In [0]:
b.shape


(4, 3)

In [0]:
b[0:,2]

array([7, 8, 6, 0])

In [0]:
b[0:,[1,2]]

array([[9, 7],
       [2, 8],
       [5, 6],
       [9, 0]])

In [0]:
b[1:,2]

array([8, 6, 0])

In [0]:
b[1:,[0,2]]

array([[3, 8],
       [4, 6],
       [2, 0]])

In [0]:
x


array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
x.reshape(3,2)

array([[2, 5],
       [8, 3],
       [6, 1]])

In [0]:
x1=x.reshape(3,2)

In [0]:
np.zeros((3,4))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [0]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [0]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [0]:
np.full((4,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [0]:
for i in dir(np):
  if 'zer' in i:
    print(i)

count_nonzero
flatnonzero
nonzero
trim_zeros
zeros
zeros_like


In [0]:
[i for i in dir(np) if 'zer' in i]

['count_nonzero',
 'flatnonzero',
 'nonzero',
 'trim_zeros',
 'zeros',
 'zeros_like']